<?php
/**
 * This function creates an article of players data on threej.in website
 */
function process_threej_msg($update){
    global $cricdb,$jarvis;
    $dataArr=[];
    $player = $update['message']['player'];
    $uid = 'p-'.urldecode($player);
    
    $sql = 'SELECT * FROM TGDATA_TABLE_3J WHERE UID LIKE ?';
    $arr = [
        [&$uid, 's']
    ];
    if($cricdb->prepare($sql, $arr) === -1){return $jarvis->e(-1, $cricdb->error);}
    if($cricdb->num_rows === 1){
        header('Content-Type: text/html');
        $result = $cricdb->fetch();
        $dataArr = json_decode($result['DATA'],true);    
    }
if(empty($dataArr) || $dataArr === 0 || !isset($dataArr['title'])){return 0;}
echo '<div style="display: flex;flex-flow: row;overflow: hidden;width: 100%;flex-wrap: wrap;">
    <div style="order: 2;max-width: 250px;">
        <img src="'.$dataArr['thumb_url'].'" alt="'.$dataArr['title'].'" style="width:200px;">
    </div>

    <div style="order: 1;max-width: 500px;font-family: fangsong;">
        <h2>'.$dataArr['title'].'</h2>
        <p style="white-space: break-spaces;">'.trim($dataArr['description']).'</p>
    </div>

</div>
<pre>
'.$dataArr['message_text'].'
</pre>
<h3>This page is automatically generated by telegram bot [<a href="https://telegram.me/cricket_info_bot" target="_blank">@cricket_info_bot</a>]</h3>';
}